"""empty message

Revision ID: 399edfda55ce
Revises: 
Create Date: 2022-11-20 12:07:22.513121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399edfda55ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name='casting_actor_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='casting_movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='casting_pkey')
    )
    # ### end Alembic commands ###
