"""empty message

Revision ID: d2f42f0544f1
Revises: 399edfda55ce
Create Date: 2022-11-24 01:01:10.507212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f42f0544f1'
down_revision = '399edfda55ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('birthdate', sa.DateTime(), nullable=True))
    op.drop_column('actors', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('actors', 'birthdate')
    # ### end Alembic commands ###
